package canopy

import "errors"

var (
	ErrInvalidCredentials         = errors.New("canopy: invalid credentials")
	ErrSignupDisabled             = errors.New("canopy: signup disabled")
	ErrUnverifiedEmail            = errors.New("canopy: unverified email")
	ErrInvalidState               = errors.New("canopy: invalid state")
	ErrInvalidToken               = errors.New("canopy: invalid token")
	ErrExpiredToken               = errors.New("canopy: expired token")
	ErrProviderFailure            = errors.New("canopy: provider failure")
	ErrStorageFailure             = errors.New("canopy: storage failure")
	ErrAccountLinking             = errors.New("canopy: account linking required")
	ErrNoRefreshToken             = errors.New("canopy: no provider refresh token")
	ErrProviderTokenRefreshFailed = errors.New("canopy: provider token refresh failed")
	ErrProviderAccountNotFound    = errors.New("canopy: provider account not found")
	ErrNotFound                   = errors.New("canopy: not found")
	ErrConflict                   = errors.New("canopy: conflict")
	ErrInvalidInput               = errors.New("canopy: invalid input")
	ErrUnauthorized               = errors.New("canopy: unauthorized")
	ErrForbidden                  = errors.New("canopy: forbidden")
	ErrUserBanned                 = errors.New("canopy: user banned")
	ErrInvalidTwoFactorCode       = errors.New("canopy: invalid two-factor code")
	ErrRecentAuthentication       = errors.New("canopy: recent authentication required")
	ErrOrganizationNotFound       = errors.New("canopy: organization not found")
	ErrNotOrganizationMember      = errors.New("canopy: not organization member")
	ErrInvitationInvalid          = errors.New("canopy: invitation invalid")
	ErrLastOrganizationOwner      = errors.New("canopy: organization must retain an owner")
)
